### ISSUE TITLE
syntax error in requirements.txt

### ISSUE THREAD

**Issue by resnant** [upura/knnFeat#4]
Hi, upura,

I found a very tiny error in "requirements.txt".
The required packages should be separated by a new line, and a comma is unnecessary here.

If run `pip install -r requirements.txt` for the present file, following error will occur.
>pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "','"

Please consider removing commas from that file.

Thank you.

**Comment by upura** [comment]
@resnant Thanks for your issue!
